#ifndef BOARD_DATA_LABELS_H
#define BOARD_DATA_LABELS_H

enum BOARD_DATA_LABELS
{
    BDL_SOCKETS_ONLINE,
    BDL_WHITE_NAME,
    BDL_BLACK_NAME,
    BDL_TURN,
    BDL_GAME_STATUS,
    BDL_MOVES,
    BDL_CASTLINGS,
    BDL_ENPASSANT,
    BDL_WHITE_TIME,
    BDL_BLACK_TIME,
    BDL_QUEUE_PLAYERS,
    BDL_QUEUE_TIME
};

#endif // BOARD_DATA_LABELS_H
