#ifndef GAME_STATUS_H
#define GAME_STATUS_H

enum GAME_STATUS
{
    //GS_

    /*
     * TURN_NONE
    WAITING_FOR_PLAYERS
    WAITING_FOR_START_CONFIRMS
    GAME_HAS_ENDED:
        WHIE_WON,
        BLACK_WON,
        DRAW,
        STAND_UP,
        GIVE_UP,
        SOCKET_LOST,
        TIMEOUT_START_3
        TIMEOUT_WHITE,
        TIMEOUT_BLACK
    RESETING
    RESET_COMPLITED
TURN_WHITE/BLACK
    FIRST_TURN
    MOVE_OK_E2E4
    BAD_MOVE_E2E4
    PROMOTE
    PROMOTED_E7E8Q
*/
};



#endif // GAME_STATUS_H
