#ifndef SEQUENCE_TYPES_H
#define SEQUENCE_TYPES_H

enum SEQUENCE_TYPE { ST_NONE, ST_BADMOVE, ST_REGULAR, ST_PROMOTE_TO_WHAT, ST_PROMOTION, ST_ENPASSANT, ST_CASTLING,
                  ST_CASTLING_KING, ST_CASTLING_ROOK, ST_REMOVING, ST_RESTORE, ST_SERVICE };

#endif // SEQUENCE_TYPES_H
